# config/routes.yaml
home:
    path: /
    controller: App\Controller\HomePageController::home

shop:
    path: /shop
    controller: App\Controller\HomePageController::shop

shopdetails:
    path: /shop/details
    controller: App\Controller\HomePageController::details

contact:
    path: /contact
    controller: App\Controller\HomePageController::contact

cart:
    path: /cart
    controller: App\Controller\HomePageController::cart

checkout:
    path: /checkout
    controller: App\Controller\HomePageController::checkout

testimonial:
    path: /testimonial
    controller: App\Controller\HomePageController::testimonial

message_reclamation_index:
    path: /message-reclamation/view/{id}
    controller: App\Controller\MessageReclamationController::index
    methods: [GET, POST]

reclamation_new:
    path: /reclamation/new
    controller: App\Controller\ReclamationController::new
    methods: [GET, POST]

reclamation_show:
    path: /reclamation/
    controller: App\Controller\ReclamationController::show
    methods: GET

reclamation_edit:
    path: /reclamation/{id}/edit
    controller: App\Controller\ReclamationController::edit
    methods: [GET, POST]

reclamation_delete:
    path: /reclamation/{id}/delete
    controller: App\Controller\ReclamationController::delete
    methods: POST

# message_reclamation_index:
#     path: /message-reclamation
#     controller: App\Controller\MessageReclamationController::index
#     methods: GET

message_reclamation_new:
    path: /message-reclamation/{reclamationId}/new
    controller: App\Controller\MessageReclamationController::new
    methods: [GET, POST]

message_reclamation_show:
    path: /message-reclamation/{id}
    controller: App\Controller\MessageReclamationController::show
    methods: GET

message_reclamation_edit:
    path: /message/{id}/edit
    controller: App\Controller\MessageReclamationController::editMessage
    methods: [GET, POST]

message_reclamation_delete:
    path: /message/{id}
    controller: App\Controller\MessageReclamationController::deleteMessage
    methods: [POST]


message_add:
    path: /message-reclamation/add
    controller: App\Controller\ReclamationController::add
    methods: [GET, POST]

ajout_produit:
    path: /produit/ajout
    controller: App\Controller\ProductsController::home

liste_produits:
    path: /produit
    controller: App\Controller\ProductsController::listeProduits

edit-produit:
    path: /produit/edit/{id}
    controller: App\Controller\ProductsController::editProduit

delete-produit:
    path: /produit/delete/{id}
    controller: App\Controller\ProductsController::deleteProduit
