# config/routes.yaml
home:
    path: /
    controller: App\Controller\HomePageController::home

app_loginpage:
    path: /login
    controller: App\Controller\LoginPageController::index

produit:
    path: /produit
    controller: App\Controller\HomePageController::produit

stock:
    resource: ../src/Controller/StockController.php
    type: annotation


# config/routes.yaml
app_entrepot:
    path: /entrepot
    controller: App\Controller\EntrepotController::index

entrepot:
    resource: ../src/Controller/EntrepotController.php
    type: annotation