# config/routes.yaml
app_loginpage:
    path: /login
    controller: App\Controller\LoginPageController::index


stock:
    resource: ../src/Controller/StockController.php
    type: annotation


# config/routes.yaml
app_entrepot:
    path: /entrepot
    controller: App\Controller\EntrepotController::index

entrepot:
    resource: ../src/Controller/EntrepotController.php
    type: annotation