# config/routes.yaml


stock:
    resource: ../src/Controller/StockController.php
    type: annotation

app_entrepot:
    path: /entrepot
    controller: App\Controller\EntrepotController::index

entrepot:
    resource: ../src/Controller/EntrepotController.php
    type: annotation