parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    google_credentials_path: '%kernel.project_dir%/config/credentials.json'
    google_token_path: '%kernel.project_dir%/config/token.json'
    google_api_key: '%env(GOOGLE_API_KEY)%'
    google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $credentialsPath: '%google_credentials_path%'
            string $tokenPath: '%google_token_path%'
            string $redirectUri: '%google_redirect_uri%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
