monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["event", "doctrine"]  # Remplacez !event et !doctrine par des chaînes de caractères simples
            console:
                type: console
                process_psr_3_messages: false
                channels: ["event", "doctrine", "console"]  # Même correction ici

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["event"]  # Remplacez !event par "event"
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["event", "doctrine"]  # Remplacez !event et !doctrine par des chaînes de caractères simples
            deprecation:
                type: stream
                channels: ["deprecation"]  # Remplacez deprecation par une chaîne de caractères simple
                path: php://stderr
                formatter: monolog.formatter.json
